
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mithila
 */
public class form5 extends javax.swing.JFrame {

    /**
     * Creates new form form5
     */
    public form5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
          
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFind_reg_no = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFind_subject_code = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtreg = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtgrade = new javax.swing.JLabel();
        txtsub = new javax.swing.JLabel();
        add_time_table3_et = new javax.swing.JButton();
        add_time_table3_et2 = new javax.swing.JButton();
        add_time_table3_et3 = new javax.swing.JButton();
        message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Add Grade ");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Reg No :");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_search_64px.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Subject Code :");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Reg No :");

        txtreg.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtreg.setText("xxxxxxxxxx");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Subject Code :");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Grade :");

        txtgrade.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtgrade.setText("xxxxxxxxxx");

        txtsub.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtsub.setText("xxxxxxxxxx");

        add_time_table3_et.setBackground(new java.awt.Color(0, 102, 102));
        add_time_table3_et.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        add_time_table3_et.setForeground(new java.awt.Color(255, 255, 255));
        add_time_table3_et.setText("Add");
        add_time_table3_et.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_time_table3_et.setBorderPainted(false);
        add_time_table3_et.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_time_table3_et.setFocusPainted(false);
        add_time_table3_et.setFocusable(false);
        add_time_table3_et.setName("exit"); // NOI18N
        add_time_table3_et.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_time_table3_etActionPerformed(evt);
            }
        });

        add_time_table3_et2.setBackground(new java.awt.Color(0, 102, 102));
        add_time_table3_et2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        add_time_table3_et2.setForeground(new java.awt.Color(255, 255, 255));
        add_time_table3_et2.setText("Clear");
        add_time_table3_et2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_time_table3_et2.setBorderPainted(false);
        add_time_table3_et2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_time_table3_et2.setFocusPainted(false);
        add_time_table3_et2.setFocusable(false);
        add_time_table3_et2.setName("exit"); // NOI18N
        add_time_table3_et2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_time_table3_et2ActionPerformed(evt);
            }
        });

        add_time_table3_et3.setBackground(new java.awt.Color(0, 102, 102));
        add_time_table3_et3.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        add_time_table3_et3.setForeground(new java.awt.Color(255, 255, 255));
        add_time_table3_et3.setText("Back");
        add_time_table3_et3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_time_table3_et3.setBorderPainted(false);
        add_time_table3_et3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_time_table3_et3.setFocusPainted(false);
        add_time_table3_et3.setFocusable(false);
        add_time_table3_et3.setName("exit"); // NOI18N
        add_time_table3_et3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_time_table3_et3ActionPerformed(evt);
            }
        });

        message.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFind_reg_no, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFind_subject_code, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(message)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsub)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtgrade, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtreg)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(add_time_table3_et, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_time_table3_et2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(add_time_table3_et3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtFind_reg_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFind_subject_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtreg))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtsub))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtgrade))
                .addGap(18, 18, 18)
                .addComponent(message)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_time_table3_et, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_time_table3_et2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_time_table3_et3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Marks mar=new Marks();
        
        if(txtFind_subject_code.getText().equals("ICT2162"))
        {
            txtgrade.setText(mar.addGradeDif(txtFind_reg_no.getText(),txtFind_subject_code.getText()));
        }
        if(txtFind_subject_code.getText().equals("ICT2153"))
        {
            txtgrade.setText(mar.addGradeDif2(txtFind_reg_no.getText(),txtFind_subject_code.getText()));
        }
        txtreg.setText(null);
        txtsub.setText(null);
        txtgrade.setText(null);
        txtgrade.setText(mar.addGrade(txtFind_reg_no.getText(),txtFind_subject_code.getText()));
        txtreg.setText(txtFind_reg_no.getText());
        txtsub.setText(txtFind_subject_code.getText());
        
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void add_time_table3_etActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_time_table3_etActionPerformed
        // TODO add your handling code here:
        if(txtreg.getText().equals("xxxxxxxxxx")||txtsub.getText().equals("xxxxxxxxxx")||txtgrade.getText().equals("xxxxxxxxxx"))
            message.setText("Grade not Selected");
        else
        {
            try {
                Connection con=MyConnection.getConnection();
                String sql="INSERT INTO grade VALUES('"+txtreg.getText()+"','"+txtsub.getText()+"','"+txtgrade.getText()+"')";
                PreparedStatement ps=con.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Data added Successfully!.");
            } catch (Exception e) {
            }
        }    
        
    }//GEN-LAST:event_add_time_table3_etActionPerformed

    private void add_time_table3_et2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_time_table3_et2ActionPerformed
        // TODO add your handling code here:
        txtFind_reg_no.setText(null);
        txtFind_subject_code.setText(null);
        txtreg.setText("xxxxxxxxxx");
        txtsub.setText("xxxxxxxxxx");
        txtgrade.setText("xxxxxxxxxx");
    }//GEN-LAST:event_add_time_table3_et2ActionPerformed

    private void add_time_table3_et3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_time_table3_et3ActionPerformed
        // TODO add your handling code here:
        form6 f6=new form6();
        f6.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_add_time_table3_et3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_time_table3_et;
    private javax.swing.JButton add_time_table3_et2;
    private javax.swing.JButton add_time_table3_et3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel message;
    private javax.swing.JTextField txtFind_reg_no;
    private javax.swing.JTextField txtFind_subject_code;
    private javax.swing.JLabel txtgrade;
    private javax.swing.JLabel txtreg;
    private javax.swing.JLabel txtsub;
    // End of variables declaration//GEN-END:variables
}
