
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mithila
 */
public class form18 extends javax.swing.JFrame {

    /**
     * Creates new form form18
     */
    public form18() {
        initComponents();
        table2ETLoard();
        table2ICTLoard();
    }
    ResultSet rs=null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        timetable2_et = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        time2_et = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        monday2_et = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tuesday2_et = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        wensday2_et = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        thursday2_et = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        friday2_et = new javax.swing.JTextField();
        add_time_table2_et = new javax.swing.JButton();
        update_et2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2_et = new javax.swing.JTable();
        message4 = new javax.swing.JLabel();
        timetable2_ict = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        time2_ict = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        monday2_ict = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tuesday2_ict = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        wensday2_ict = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        thursday2_ict = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        friday2_ict = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        table2_ict = new javax.swing.JTable();
        add_time_table2_ict = new javax.swing.JButton();
        update_ict2 = new javax.swing.JButton();
        message5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setLayout(new java.awt.CardLayout());

        timetable2_et.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timet.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel11.setText("Level 2 Time Table ET");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setText("Time :");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setText("Monday :");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setText("Tuesday  :");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setText("Wensday :");

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setText("Thursday :");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setText("Friday :");

        add_time_table2_et.setBackground(new java.awt.Color(0, 102, 102));
        add_time_table2_et.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        add_time_table2_et.setForeground(new java.awt.Color(255, 255, 255));
        add_time_table2_et.setText("Add");
        add_time_table2_et.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_time_table2_et.setBorderPainted(false);
        add_time_table2_et.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_time_table2_et.setFocusPainted(false);
        add_time_table2_et.setFocusable(false);
        add_time_table2_et.setName("exit"); // NOI18N
        add_time_table2_et.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_time_table2_etActionPerformed(evt);
            }
        });

        update_et2.setBackground(new java.awt.Color(0, 102, 102));
        update_et2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        update_et2.setForeground(new java.awt.Color(255, 255, 255));
        update_et2.setText("Update");
        update_et2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update_et2.setBorderPainted(false);
        update_et2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_et2.setFocusPainted(false);
        update_et2.setFocusable(false);
        update_et2.setName("exit"); // NOI18N
        update_et2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_et2ActionPerformed(evt);
            }
        });

        table2_et.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        table2_et.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Time", "Monday", "Tuesday", "Wensday", "Thursday", "Friday"
            }
        ));
        table2_et.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2_etMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table2_et);

        message4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        message4.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout timetable2_etLayout = new javax.swing.GroupLayout(timetable2_et);
        timetable2_et.setLayout(timetable2_etLayout);
        timetable2_etLayout.setHorizontalGroup(
            timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timetable2_etLayout.createSequentialGroup()
                .addGroup(timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timetable2_etLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(timetable2_etLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(timetable2_etLayout.createSequentialGroup()
                                .addGroup(timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addGroup(timetable2_etLayout.createSequentialGroup()
                                        .addGroup(timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel16))
                                        .addGap(27, 27, 27)
                                        .addGroup(timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(time2_et, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tuesday2_et, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(monday2_et, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timetable2_etLayout.createSequentialGroup()
                                .addComponent(message4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(add_time_table2_et, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(update_et2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(337, 337, 337))
                            .addGroup(timetable2_etLayout.createSequentialGroup()
                                .addGroup(timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(timetable2_etLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(21, 21, 21)
                                        .addComponent(wensday2_et, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(timetable2_etLayout.createSequentialGroup()
                                            .addComponent(jLabel19)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(friday2_et, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(timetable2_etLayout.createSequentialGroup()
                                            .addComponent(jLabel18)
                                            .addGap(27, 27, 27)
                                            .addComponent(thursday2_et, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(85, 85, 85))
        );
        timetable2_etLayout.setVerticalGroup(
            timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timetable2_etLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timetable2_etLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel11)
                        .addGap(24, 24, 24))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timetable2_etLayout.createSequentialGroup()
                        .addGroup(timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(time2_et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(monday2_et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tuesday2_et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(wensday2_et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(thursday2_et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(friday2_et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timetable2_etLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(timetable2_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(update_et2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_time_table2_et, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(timetable2_etLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(message4)))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jPanel2.add(timetable2_et, "card2");

        timetable2_ict.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timet.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel20.setText("Level 2 Time Table ICT");

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel21.setText("Time :");

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel22.setText("Monday :");

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel23.setText("Tuesday  :");

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setText("Wensday :");

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel25.setText("Thursday :");

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel26.setText("Friday :");

        table2_ict.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        table2_ict.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Time", "Monday", "Tuesday", "Wensday", "Thursday", "Friday"
            }
        ));
        table2_ict.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2_ictMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table2_ict);

        add_time_table2_ict.setBackground(new java.awt.Color(0, 102, 102));
        add_time_table2_ict.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        add_time_table2_ict.setForeground(new java.awt.Color(255, 255, 255));
        add_time_table2_ict.setText("Add");
        add_time_table2_ict.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_time_table2_ict.setBorderPainted(false);
        add_time_table2_ict.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_time_table2_ict.setFocusPainted(false);
        add_time_table2_ict.setFocusable(false);
        add_time_table2_ict.setName("exit"); // NOI18N
        add_time_table2_ict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_time_table2_ictActionPerformed(evt);
            }
        });

        update_ict2.setBackground(new java.awt.Color(0, 102, 102));
        update_ict2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        update_ict2.setForeground(new java.awt.Color(255, 255, 255));
        update_ict2.setText("Update");
        update_ict2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update_ict2.setBorderPainted(false);
        update_ict2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_ict2.setFocusPainted(false);
        update_ict2.setFocusable(false);
        update_ict2.setName("exit"); // NOI18N
        update_ict2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_ict2ActionPerformed(evt);
            }
        });

        message5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        message5.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout timetable2_ictLayout = new javax.swing.GroupLayout(timetable2_ict);
        timetable2_ict.setLayout(timetable2_ictLayout);
        timetable2_ictLayout.setHorizontalGroup(
            timetable2_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timetable2_ictLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(timetable2_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timetable2_ictLayout.createSequentialGroup()
                        .addGroup(timetable2_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timetable2_ictLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(57, 57, 57)
                                .addGroup(timetable2_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(time2_ict, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(monday2_ict, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(timetable2_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, timetable2_ictLayout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addGap(27, 27, 27)
                                    .addComponent(thursday2_ict, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, timetable2_ictLayout.createSequentialGroup()
                                    .addComponent(jLabel26)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(friday2_ict, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(timetable2_ictLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(21, 21, 21)
                                .addComponent(wensday2_ict, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timetable2_ictLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(27, 27, 27)
                                .addComponent(tuesday2_ict, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addGroup(timetable2_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(timetable2_ictLayout.createSequentialGroup()
                                .addComponent(add_time_table2_ict, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(update_ict2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58))
                    .addGroup(timetable2_ictLayout.createSequentialGroup()
                        .addGroup(timetable2_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(message5, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        timetable2_ictLayout.setVerticalGroup(
            timetable2_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timetable2_ictLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(timetable2_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timetable2_ictLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel20)
                        .addGap(24, 24, 24))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(timetable2_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timetable2_ictLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addGroup(timetable2_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_time_table2_ict, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update_ict2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(timetable2_ictLayout.createSequentialGroup()
                        .addGroup(timetable2_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(time2_ict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(timetable2_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(monday2_ict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(timetable2_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(tuesday2_ict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(timetable2_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(wensday2_ict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(timetable2_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(thursday2_ict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(timetable2_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(friday2_ict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(message5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jPanel2.add(timetable2_ict, "card3");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cource.png"))); // NOI18N
        jLabel9.setText("ENT");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cource.png"))); // NOI18N
        jLabel12.setText("ICT");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit3.png"))); // NOI18N
        jLabel28.setText("Exit");
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(109, 109, 109)
                .addComponent(jLabel12)
                .addGap(116, 116, 116)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_time_table2_etActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_time_table2_etActionPerformed
        // TODO add your handling code here:
        message4.setText(null);
        if(time2_et.getText().equals(""))
        message4.setText("You must have to mention time!!..");
        else{
            Admin adm=new Admin();
            adm.addTimeTableET2(time2_et.getText(),monday2_et.getText(),tuesday2_et.getText(),wensday2_et.getText(),thursday2_et.getText(),friday2_et.getText());
            table2ETLoard();
            time2_et.setText(null);
            monday2_et.setText(null);
            tuesday2_et.setText(null);
            wensday2_et.setText(null);
            thursday2_et.setText(null);
            friday2_et.setText(null);
        }
    }//GEN-LAST:event_add_time_table2_etActionPerformed

    private void update_et2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_et2ActionPerformed
        message4.setText(null);
        if(time2_et.getText().equals(""))
        message4.setText("You must have to mention time!!..");
        else{
            Admin adm=new Admin();
            adm.updateTimeTableET2(time2_et.getText(),monday2_et.getText(),tuesday2_et.getText(),wensday2_et.getText(),thursday2_et.getText(),friday2_et.getText());
            table2ETLoard();
        }

    }//GEN-LAST:event_update_et2ActionPerformed

    private void table2_etMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2_etMouseClicked
        // TODO add your handling code here:
        int r=table2_et.getSelectedRow();
        String time=table2_et.getValueAt(r, 0).toString();
        String monday=table2_et.getValueAt(r, 1).toString();
        String tuesday=table2_et.getValueAt(r, 2).toString();
        String wensday=table2_et.getValueAt(r, 3).toString();
        String thursday=table2_et.getValueAt(r, 4).toString();
        String friday=table2_et.getValueAt(r, 5).toString();

        //setting values to text fields
        time2_et.setText(time);
        monday2_et.setText(monday);
        tuesday2_et.setText(tuesday);
        wensday2_et.setText(wensday);
        thursday2_et.setText(thursday);
        friday2_et.setText(friday);
    }//GEN-LAST:event_table2_etMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        boolean flag=true;
        timetable2_et.setVisible(flag);
        flag=false;
        timetable2_ict.setVisible(flag);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        boolean flag=true;
        timetable2_ict.setVisible(flag);
        flag=false;
        timetable2_et.setVisible(flag);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        form15 f15=new form15();
        f15.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel28MouseClicked

    private void table2_ictMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2_ictMouseClicked
        // TODO add your handling code here:
        int r=table2_ict.getSelectedRow();
        String time=table2_ict.getValueAt(r, 0).toString();
        String monday=table2_ict.getValueAt(r, 1).toString();
        String tuesday=table2_ict.getValueAt(r, 2).toString();
        String wensday=table2_ict.getValueAt(r, 3).toString();
        String thursday=table2_ict.getValueAt(r, 4).toString();
        String friday=table2_ict.getValueAt(r, 5).toString();

        //setting values to text fields
        time2_ict.setText(time);
        monday2_ict.setText(monday);
        tuesday2_ict.setText(tuesday);
        wensday2_ict.setText(wensday);
        thursday2_ict.setText(thursday);
        friday2_ict.setText(friday);
    }//GEN-LAST:event_table2_ictMouseClicked

    private void add_time_table2_ictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_time_table2_ictActionPerformed
        // TODO add your handling code here:
        message5.setText(null);
        if(time2_ict.getText().equals(""))
        message5.setText("You must have to mention time!!..");
        else{
            Admin adm=new Admin();
            adm.addTimeTableICT2(time2_ict.getText(),monday2_ict.getText(),tuesday2_ict.getText(),wensday2_ict.getText(),thursday2_ict.getText(),friday2_ict.getText());
            table2ICTLoard();
            time2_ict.setText(null);
            monday2_ict.setText(null);
            tuesday2_ict.setText(null);
            wensday2_ict.setText(null);
            thursday2_ict.setText(null);
            friday2_ict.setText(null);
        }
    }//GEN-LAST:event_add_time_table2_ictActionPerformed

    private void update_ict2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_ict2ActionPerformed
        // TODO add your handling code here:
        message5.setText(null);
        if(time2_ict.getText().equals(""))
        message5.setText("You must have to mention time!!..");
        else{
            Admin adm=new Admin();
            adm.updateTimeTableICT2(time2_ict.getText(),monday2_ict.getText(),tuesday2_ict.getText(),wensday2_ict.getText(),thursday2_ict.getText(),friday2_ict.getText());
            table2ICTLoard();
            time2_ict.setText(null);
            monday2_ict.setText(null);
            tuesday2_ict.setText(null);
            wensday2_ict.setText(null);
            thursday2_ict.setText(null);
            friday2_ict.setText(null);
        }
    }//GEN-LAST:event_update_ict2ActionPerformed
    public void table2ETLoard()
    {
        Connection con=MyConnection.getConnection();
        String sql="SELECT *FROM timetable_level2_et";
        try {
            PreparedStatement ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            
            table2_et.setModel(DbUtils.resultSetToTableModel(rs));
            //table1_et.setModel(();
        } catch (SQLException ex) {
            Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }  

     public void table2ICTLoard()
    {
        Connection con=MyConnection.getConnection();
        String sql="SELECT *FROM timetable_level2_ict";
        try {
            PreparedStatement ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            
            table2_ict.setModel(DbUtils.resultSetToTableModel(rs));
            //table1_et.setModel(();
        } catch (SQLException ex) {
            Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form18.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form18.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form18.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form18.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form18().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_time_table2_et;
    private javax.swing.JButton add_time_table2_ict;
    private javax.swing.JTextField friday2_et;
    private javax.swing.JTextField friday2_ict;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel message4;
    private javax.swing.JLabel message5;
    private javax.swing.JTextField monday2_et;
    private javax.swing.JTextField monday2_ict;
    private javax.swing.JTable table2_et;
    private javax.swing.JTable table2_ict;
    private javax.swing.JTextField thursday2_et;
    private javax.swing.JTextField thursday2_ict;
    public javax.swing.JTextField time2_et;
    public javax.swing.JTextField time2_ict;
    private javax.swing.JPanel timetable2_et;
    private javax.swing.JPanel timetable2_ict;
    private javax.swing.JTextField tuesday2_et;
    private javax.swing.JTextField tuesday2_ict;
    private javax.swing.JButton update_et2;
    private javax.swing.JButton update_ict2;
    private javax.swing.JTextField wensday2_et;
    private javax.swing.JTextField wensday2_ict;
    // End of variables declaration//GEN-END:variables
}
