
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;
/*import org.apache.commons.dbutils.DbUtils;
import org.apache.commons.dbutils.ResultSetHandler;
import org.apache.commons.dbutils.QueryRunner;*/
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mithila
 */
public class form17 extends javax.swing.JFrame {
    ResultSet rs=null;
    /**
     * Creates new form form17
     */
    public form17() {
        initComponents();
        table1EtLoard();
        table1BSTLoard();
        table1ICTLoard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        timetable_et = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        add_time_table_et1 = new javax.swing.JButton();
        time1_et = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        thursday1_et = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        friday1_et = new javax.swing.JTextField();
        update_et1 = new javax.swing.JButton();
        wensday1_et = new javax.swing.JTextField();
        tuesday1_et = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1_et = new javax.swing.JTable();
        monday1_et = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        timetable_ict = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        time1_ict1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        monday1_ict1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tuesday1_ict1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        wensday1_ict1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        thursday1_ict1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        friday1_ict1 = new javax.swing.JTextField();
        add_time_table_ict = new javax.swing.JButton();
        update_ict = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table1_ict1 = new javax.swing.JTable();
        message3 = new javax.swing.JLabel();
        timetable_bst = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        time1_bst1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        monday1_bst1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tuesday1_bst1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        wensday1_bst1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        thursday1_bst1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        friday1_bst1 = new javax.swing.JTextField();
        add_time_table_bst1 = new javax.swing.JButton();
        update_bst1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1_bst1 = new javax.swing.JTable();
        message2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setLayout(new java.awt.CardLayout());

        timetable_et.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timet.png"))); // NOI18N

        add_time_table_et1.setBackground(new java.awt.Color(0, 102, 102));
        add_time_table_et1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        add_time_table_et1.setForeground(new java.awt.Color(255, 255, 255));
        add_time_table_et1.setText("Add");
        add_time_table_et1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_time_table_et1.setBorderPainted(false);
        add_time_table_et1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_time_table_et1.setFocusPainted(false);
        add_time_table_et1.setFocusable(false);
        add_time_table_et1.setName("exit"); // NOI18N
        add_time_table_et1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_time_table_et1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Friday :");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel2.setText("Level 1 Time Table ENT");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Time :");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Wensday :");

        update_et1.setBackground(new java.awt.Color(0, 102, 102));
        update_et1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        update_et1.setForeground(new java.awt.Color(255, 255, 255));
        update_et1.setText("Update");
        update_et1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update_et1.setBorderPainted(false);
        update_et1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_et1.setFocusPainted(false);
        update_et1.setFocusable(false);
        update_et1.setName("exit"); // NOI18N
        update_et1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_et1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Monday :");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Tuesday  :");

        table1_et.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        table1_et.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Time", "Monday", "Tuesday", "Wensday", "Thursday", "Friday"
            }
        ));
        table1_et.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1_etMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1_et);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Thursday :");

        message.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        message.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout timetable_etLayout = new javax.swing.GroupLayout(timetable_et);
        timetable_et.setLayout(timetable_etLayout);
        timetable_etLayout.setHorizontalGroup(
            timetable_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timetable_etLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(timetable_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(timetable_etLayout.createSequentialGroup()
                        .addGroup(timetable_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(timetable_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tuesday1_et, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monday1_et, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(time1_et, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(timetable_etLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(21, 21, 21)
                        .addComponent(wensday1_et, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(timetable_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(timetable_etLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(friday1_et, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(timetable_etLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(27, 27, 27)
                            .addComponent(thursday1_et, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(timetable_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(timetable_etLayout.createSequentialGroup()
                        .addComponent(add_time_table_et1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(update_et1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(timetable_etLayout.createSequentialGroup()
                .addGroup(timetable_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timetable_etLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(timetable_etLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(message)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        timetable_etLayout.setVerticalGroup(
            timetable_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timetable_etLayout.createSequentialGroup()
                .addGroup(timetable_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timetable_etLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(timetable_etLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(timetable_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timetable_etLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(timetable_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(time1_et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(timetable_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(monday1_et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(timetable_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tuesday1_et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(timetable_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(wensday1_et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(timetable_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(thursday1_et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(timetable_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(friday1_et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(timetable_etLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(update_et1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(add_time_table_et1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(86, 86, 86)
                .addComponent(message)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel4.add(timetable_et, "card2");

        timetable_ict.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timet.png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel21.setText("Level 1 Time Table ICT");

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel22.setText("Time :");

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel23.setText("Monday :");

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setText("Tuesday  :");

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel25.setText("Wensday :");

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel26.setText("Thursday :");

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel27.setText("Friday :");

        add_time_table_ict.setBackground(new java.awt.Color(0, 102, 102));
        add_time_table_ict.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        add_time_table_ict.setForeground(new java.awt.Color(255, 255, 255));
        add_time_table_ict.setText("Add");
        add_time_table_ict.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_time_table_ict.setBorderPainted(false);
        add_time_table_ict.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_time_table_ict.setFocusPainted(false);
        add_time_table_ict.setFocusable(false);
        add_time_table_ict.setName("exit"); // NOI18N
        add_time_table_ict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_time_table_ictActionPerformed(evt);
            }
        });

        update_ict.setBackground(new java.awt.Color(0, 102, 102));
        update_ict.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        update_ict.setForeground(new java.awt.Color(255, 255, 255));
        update_ict.setText("Update");
        update_ict.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update_ict.setBorderPainted(false);
        update_ict.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_ict.setFocusPainted(false);
        update_ict.setFocusable(false);
        update_ict.setName("exit"); // NOI18N
        update_ict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_ictActionPerformed(evt);
            }
        });

        table1_ict1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        table1_ict1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Time", "Monday", "Tuesday", "Wensday", "Thursday", "Friday"
            }
        ));
        table1_ict1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1_ict1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table1_ict1);

        message3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        message3.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout timetable_ictLayout = new javax.swing.GroupLayout(timetable_ict);
        timetable_ict.setLayout(timetable_ictLayout);
        timetable_ictLayout.setHorizontalGroup(
            timetable_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timetable_ictLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(timetable_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timetable_ictLayout.createSequentialGroup()
                        .addComponent(message3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(timetable_ictLayout.createSequentialGroup()
                        .addGroup(timetable_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(timetable_ictLayout.createSequentialGroup()
                                .addGroup(timetable_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel24))
                                .addGap(27, 27, 27)
                                .addGroup(timetable_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(time1_ict1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timetable_ictLayout.createSequentialGroup()
                                        .addGroup(timetable_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tuesday1_ict1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(monday1_ict1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                                        .addGroup(timetable_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(timetable_ictLayout.createSequentialGroup()
                                                .addComponent(add_time_table_ict, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(update_ict, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(timetable_ictLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(21, 21, 21)
                                .addComponent(wensday1_ict1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(timetable_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(timetable_ictLayout.createSequentialGroup()
                                    .addComponent(jLabel27)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(friday1_ict1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(timetable_ictLayout.createSequentialGroup()
                                    .addComponent(jLabel26)
                                    .addGap(27, 27, 27)
                                    .addComponent(thursday1_ict1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel21))
                        .addGap(107, 107, 107))))
        );
        timetable_ictLayout.setVerticalGroup(
            timetable_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timetable_ictLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(timetable_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timetable_ictLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel21)
                        .addGap(24, 24, 24))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(timetable_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(time1_ict1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(timetable_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timetable_ictLayout.createSequentialGroup()
                        .addGroup(timetable_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(monday1_ict1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(timetable_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(tuesday1_ict1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(timetable_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(wensday1_ict1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(timetable_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(thursday1_ict1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(timetable_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(friday1_ict1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(timetable_ictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(update_ict, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(add_time_table_ict, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79)
                .addComponent(message3)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel4.add(timetable_ict, "card3");

        timetable_bst.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timet.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel11.setText("Level 1 Time Table BST");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setText("Time :");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setText("Monday :");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setText("Tuesday  :");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setText("Wensday :");

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setText("Thursday :");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setText("Friday :");

        add_time_table_bst1.setBackground(new java.awt.Color(0, 102, 102));
        add_time_table_bst1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        add_time_table_bst1.setForeground(new java.awt.Color(255, 255, 255));
        add_time_table_bst1.setText("Add");
        add_time_table_bst1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_time_table_bst1.setBorderPainted(false);
        add_time_table_bst1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_time_table_bst1.setFocusPainted(false);
        add_time_table_bst1.setFocusable(false);
        add_time_table_bst1.setName("exit"); // NOI18N
        add_time_table_bst1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_time_table_bst1ActionPerformed(evt);
            }
        });

        update_bst1.setBackground(new java.awt.Color(0, 102, 102));
        update_bst1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        update_bst1.setForeground(new java.awt.Color(255, 255, 255));
        update_bst1.setText("Update");
        update_bst1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update_bst1.setBorderPainted(false);
        update_bst1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_bst1.setFocusPainted(false);
        update_bst1.setFocusable(false);
        update_bst1.setName("exit"); // NOI18N
        update_bst1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_bst1ActionPerformed(evt);
            }
        });

        table1_bst1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        table1_bst1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Time", "Monday", "Tuesday", "Wensday", "Thursday", "Friday"
            }
        ));
        table1_bst1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1_bst1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table1_bst1);

        message2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        message2.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout timetable_bstLayout = new javax.swing.GroupLayout(timetable_bst);
        timetable_bst.setLayout(timetable_bstLayout);
        timetable_bstLayout.setHorizontalGroup(
            timetable_bstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timetable_bstLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(timetable_bstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timetable_bstLayout.createSequentialGroup()
                        .addComponent(message2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(timetable_bstLayout.createSequentialGroup()
                        .addGroup(timetable_bstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(timetable_bstLayout.createSequentialGroup()
                                .addGroup(timetable_bstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16))
                                .addGap(27, 27, 27)
                                .addGroup(timetable_bstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(time1_bst1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timetable_bstLayout.createSequentialGroup()
                                        .addGroup(timetable_bstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tuesday1_bst1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(monday1_bst1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                        .addGroup(timetable_bstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(timetable_bstLayout.createSequentialGroup()
                                                .addComponent(add_time_table_bst1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(update_bst1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(timetable_bstLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(21, 21, 21)
                                .addComponent(wensday1_bst1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(timetable_bstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(timetable_bstLayout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(friday1_bst1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(timetable_bstLayout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addGap(27, 27, 27)
                                    .addComponent(thursday1_bst1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel11))
                        .addGap(92, 92, 92))))
        );
        timetable_bstLayout.setVerticalGroup(
            timetable_bstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timetable_bstLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(timetable_bstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timetable_bstLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel11)
                        .addGap(24, 24, 24))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(timetable_bstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(time1_bst1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(timetable_bstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timetable_bstLayout.createSequentialGroup()
                        .addGroup(timetable_bstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(monday1_bst1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(timetable_bstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tuesday1_bst1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(timetable_bstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(wensday1_bst1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(timetable_bstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(thursday1_bst1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(timetable_bstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(friday1_bst1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(timetable_bstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(update_bst1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(add_time_table_bst1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77)
                .addComponent(message2)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel4.add(timetable_bst, "card4");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cource.png"))); // NOI18N
        jLabel12.setText("ICT");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cource.png"))); // NOI18N
        jLabel14.setText("BST");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cource.png"))); // NOI18N
        jLabel9.setText("ENT");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit3.png"))); // NOI18N
        jLabel28.setText("Exit");
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(89, 89, 89)
                .addComponent(jLabel12)
                .addGap(94, 94, 94)
                .addComponent(jLabel14)
                .addGap(87, 87, 87)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addGap(39, 39, 39))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_time_table_et1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_time_table_et1ActionPerformed
        // TODO add your handling code here:
        if(time1_et.getText().equals(""))
        message.setText("You must have to mention time!!..");
        else{
            Admin adm=new Admin();
            adm.addTimeTableET1(time1_et.getText(),monday1_et.getText(),tuesday1_et.getText(),wensday1_et.getText(),thursday1_et.getText(),friday1_et.getText());
             table1EtLoard();
            time1_et.setText(null);
            monday1_et.setText(null);
            tuesday1_et.setText(null);
            wensday1_et.setText(null);
            thursday1_et.setText(null);
            friday1_et.setText(null);
        }
    }//GEN-LAST:event_add_time_table_et1ActionPerformed

    private void update_et1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_et1ActionPerformed
        if(time1_et.getText().equals(""))
        message.setText("You must have to mention time!!..");
        else{
            Admin adm=new Admin();
            adm.updateTimeTableET1(time1_et.getText(),monday1_et.getText(),tuesday1_et.getText(),wensday1_et.getText(),thursday1_et.getText(),friday1_et.getText());
            table1EtLoard();
            time1_et.setText(null);
            monday1_et.setText(null);
            tuesday1_et.setText(null);
            wensday1_et.setText(null);
            thursday1_et.setText(null);
            friday1_et.setText(null);
        }
    }//GEN-LAST:event_update_et1ActionPerformed

    private void table1_etMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1_etMouseClicked
        // TODO add your handling code here:
        //getting values from table
        int r=table1_et.getSelectedRow();
        String time=table1_et.getValueAt(r, 0).toString();
        String monday=table1_et.getValueAt(r, 1).toString();
        String tuesday=table1_et.getValueAt(r, 2).toString();
        String wensday=table1_et.getValueAt(r, 3).toString();
        String thursday=table1_et.getValueAt(r, 4).toString();
        String friday=table1_et.getValueAt(r, 5).toString();
        
        //setting values to text fields
        time1_et.setText(time);
        monday1_et.setText(monday);
        tuesday1_et.setText(tuesday);
        wensday1_et.setText(wensday);
        thursday1_et.setText(thursday);
        friday1_et.setText(friday);
    }//GEN-LAST:event_table1_etMouseClicked

    private void add_time_table_bst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_time_table_bst1ActionPerformed
        // TODO add your handling code here:
        message2.setText(null);
        if(time1_bst1.getText().equals(""))
        message2.setText("You must have to mention time!!..");
        else{
            Admin adm=new Admin();
            adm.addTimeTableBST1(time1_bst1.getText(),monday1_bst1.getText(),tuesday1_bst1.getText(),wensday1_bst1.getText(),thursday1_bst1.getText(),friday1_bst1.getText());
            table1BSTLoard();
            time1_bst1.setText(null);
            monday1_bst1.setText(null);
            tuesday1_bst1.setText(null);
            wensday1_bst1.setText(null);
            thursday1_bst1.setText(null);
            friday1_bst1.setText(null);
        }
    }//GEN-LAST:event_add_time_table_bst1ActionPerformed

    private void update_bst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_bst1ActionPerformed
        message2.setText(null);
        if(time1_bst1.getText().equals(""))
        message2.setText("You must have to mention time!!..");
        else{
            Admin adm=new Admin();
            adm.updateTimeTableBST1(time1_bst1.getText(),monday1_bst1.getText(),tuesday1_bst1.getText(),wensday1_bst1.getText(),thursday1_bst1.getText(),friday1_bst1.getText());
            table1BSTLoard();
            time1_bst1.setText(null);
            monday1_bst1.setText(null);
            tuesday1_bst1.setText(null);
            wensday1_bst1.setText(null);
            thursday1_bst1.setText(null);
            friday1_bst1.setText(null);
        }
        
    }//GEN-LAST:event_update_bst1ActionPerformed

    private void table1_bst1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1_bst1MouseClicked
        // TODO add your handling code here:
        int r=table1_bst1.getSelectedRow();
        String time=table1_bst1.getValueAt(r, 0).toString();
        String monday=table1_bst1.getValueAt(r, 1).toString();
        String tuesday=table1_bst1.getValueAt(r, 2).toString();
        String wensday=table1_bst1.getValueAt(r, 3).toString();
        String thursday=table1_bst1.getValueAt(r, 4).toString();
        String friday=table1_bst1.getValueAt(r, 5).toString();
        
        //setting values to text fields
        time1_bst1.setText(time);
        monday1_bst1.setText(monday);
        tuesday1_bst1.setText(tuesday);
        wensday1_bst1.setText(wensday);
        thursday1_bst1.setText(thursday);
        friday1_bst1.setText(friday);
    }//GEN-LAST:event_table1_bst1MouseClicked

    private void add_time_table_ictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_time_table_ictActionPerformed
        // TODO add your handling code here:
        if(time1_ict1.getText().equals(""))
        message3.setText("You must have to mention time!!..");
        else{
            Admin adm=new Admin();
            adm.addTimeTableICT1(time1_ict1.getText(),monday1_ict1.getText(),tuesday1_ict1.getText(),wensday1_ict1.getText(),thursday1_ict1.getText(),friday1_ict1.getText());
            table1ICTLoard();
            time1_ict1.setText(null);
            monday1_ict1.setText(null);
            tuesday1_ict1.setText(null);
            wensday1_ict1.setText(null);
            thursday1_ict1.setText(null);
            friday1_ict1.setText(null);
        }
        
    }//GEN-LAST:event_add_time_table_ictActionPerformed

    private void update_ictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_ictActionPerformed
        // TODO add your handling code here:
        if(time1_ict1.getText().equals(""))
        message3.setText("You must have to mention time!!..");
        else{
            Admin adm=new Admin();
            adm.updateTimeTableICT1(time1_ict1.getText(),monday1_ict1.getText(),tuesday1_ict1.getText(),wensday1_ict1.getText(),thursday1_ict1.getText(),friday1_ict1.getText());
            table1ICTLoard();
            time1_ict1.setText(null);
            monday1_ict1.setText(null);
            tuesday1_ict1.setText(null);
            wensday1_ict1.setText(null);
            thursday1_ict1.setText(null);
            friday1_ict1.setText(null);
        }
    }//GEN-LAST:event_update_ictActionPerformed

    private void table1_ict1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1_ict1MouseClicked
        // TODO add your handling code here:
         int r=table1_ict1.getSelectedRow();
        String time=table1_ict1.getValueAt(r, 0).toString();
        String monday=table1_ict1.getValueAt(r, 1).toString();
        String tuesday=table1_ict1.getValueAt(r, 2).toString();
        String wensday=table1_ict1.getValueAt(r, 3).toString();
        String thursday=table1_ict1.getValueAt(r, 4).toString();
        String friday=table1_ict1.getValueAt(r, 5).toString();
        
        //setting values to text fields
        time1_ict1.setText(time);
        monday1_ict1.setText(monday);
        tuesday1_ict1.setText(tuesday);
        wensday1_ict1.setText(wensday);
        thursday1_ict1.setText(thursday);
        friday1_ict1.setText(friday);
    }//GEN-LAST:event_table1_ict1MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        form15 f15=new form15();
        f15.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        boolean flag=true;
        timetable_et.setVisible(flag);
        flag=false;
        timetable_bst.setVisible(flag);
        timetable_ict.setVisible(flag);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        boolean flag=true;
        timetable_ict.setVisible(flag);
        flag=false;
        timetable_bst.setVisible(flag);
        timetable_et.setVisible(flag);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
         boolean flag=true;
         timetable_bst.setVisible(flag);
         flag=false;
         timetable_et.setVisible(flag);
         timetable_ict.setVisible(flag);
    }//GEN-LAST:event_jLabel14MouseClicked

    public void table1EtLoard()
    {
        Connection con=MyConnection.getConnection();
        String sql="SELECT *FROM timetable_level1_et";
        try {
            PreparedStatement ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            
            table1_et.setModel(DbUtils.resultSetToTableModel(rs));
            //table1_et.setModel(();
        } catch (SQLException ex) {
            Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
        }
    }  
    
    public void table1BSTLoard()
    {
        Connection con=MyConnection.getConnection();
        String sql="SELECT *FROM timetable_level1_bst";
        try {
            PreparedStatement ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            
            table1_bst1.setModel(DbUtils.resultSetToTableModel(rs));
            //table1_et.setModel(();
        } catch (SQLException ex) {
            Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
        }
    }  
    public void table1ICTLoard()
    {
        Connection con=MyConnection.getConnection();
        String sql="SELECT *FROM timetable_level1_ict";
        try {
            PreparedStatement ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            
            table1_ict1.setModel(DbUtils.resultSetToTableModel(rs));
            //table1_et.setModel(();
        } catch (SQLException ex) {
            Logger.getLogger(form17.class.getName()).log(Level.SEVERE, null, ex);
        }
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form17().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_time_table_bst1;
    private javax.swing.JButton add_time_table_et1;
    private javax.swing.JButton add_time_table_ict;
    private javax.swing.JTextField friday1_bst1;
    private javax.swing.JTextField friday1_et;
    private javax.swing.JTextField friday1_ict1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel message;
    private javax.swing.JLabel message2;
    private javax.swing.JLabel message3;
    private javax.swing.JTextField monday1_bst1;
    private javax.swing.JTextField monday1_et;
    private javax.swing.JTextField monday1_ict1;
    private javax.swing.JTable table1_bst1;
    private javax.swing.JTable table1_et;
    private javax.swing.JTable table1_ict1;
    private javax.swing.JTextField thursday1_bst1;
    private javax.swing.JTextField thursday1_et;
    private javax.swing.JTextField thursday1_ict1;
    public javax.swing.JTextField time1_bst1;
    public javax.swing.JTextField time1_et;
    public javax.swing.JTextField time1_ict1;
    private javax.swing.JPanel timetable_bst;
    private javax.swing.JPanel timetable_et;
    private javax.swing.JPanel timetable_ict;
    private javax.swing.JTextField tuesday1_bst1;
    private javax.swing.JTextField tuesday1_et;
    private javax.swing.JTextField tuesday1_ict1;
    private javax.swing.JButton update_bst1;
    private javax.swing.JButton update_et1;
    private javax.swing.JButton update_ict;
    private javax.swing.JTextField wensday1_bst1;
    private javax.swing.JTextField wensday1_et;
    private javax.swing.JTextField wensday1_ict1;
    // End of variables declaration//GEN-END:variables
}
