
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mithila
 */
public class form13 extends javax.swing.JFrame {

    /**
     * Creates new form form13
     */
    public form13() {
        initComponents();
        showdata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        click_create = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        click_edit = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        click_delete = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        p_create = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCource_code = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCourse_Title = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCourse_co = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        com_dep = new javax.swing.JComboBox<>();
        add_cource = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        p_remove = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        btn_search_d = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtCourse_code1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtCourse_title1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtCouse_co1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtdep1 = new javax.swing.JTextField();
        btn_remove = new javax.swing.JButton();
        btn_back3 = new javax.swing.JButton();
        btn_back4 = new javax.swing.JButton();
        p_update = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSearch_u = new javax.swing.JTextField();
        btn_search_course_u = new javax.swing.JButton();
        txtCourse_code_u = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCourse_title_u = new javax.swing.JTextField();
        txtCouse_co_u = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtdep_u = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        btn_back1 = new javax.swing.JButton();
        btn_back2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_course = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        click_create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Register-Now-Icon-e1429875051197.png"))); // NOI18N
        click_create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        click_create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                click_createMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setText("Create");

        click_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-event-icon - Copy copy.png"))); // NOI18N
        click_edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        click_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                click_editMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setText("Edit Courses");

        click_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rem copy.png"))); // NOI18N
        click_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        click_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                click_deleteMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setText("Remove Courses");

        jPanel2.setLayout(new java.awt.CardLayout());

        p_create.setBackground(new java.awt.Color(255, 255, 255));
        p_create.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Add Course Units");
        p_create.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 63, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Course Code :");
        p_create.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        txtCource_code.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        p_create.add(txtCource_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 315, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Course Title :");
        p_create.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        txtCourse_Title.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        p_create.add(txtCourse_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 315, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Course Coordinator :");
        p_create.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        txtCourse_co.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        p_create.add(txtCourse_co, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 315, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Department :");
        p_create.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        com_dep.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        com_dep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Engineering Technology", "Information Communication Technology", "Bio System Technology", "Multi Disciplinary" }));
        p_create.add(com_dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 315, -1));

        add_cource.setBackground(new java.awt.Color(0, 102, 102));
        add_cource.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        add_cource.setForeground(new java.awt.Color(255, 255, 255));
        add_cource.setText("Add");
        add_cource.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_cource.setBorderPainted(false);
        add_cource.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_cource.setFocusPainted(false);
        add_cource.setFocusable(false);
        add_cource.setName("exit"); // NOI18N
        add_cource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_courceActionPerformed(evt);
            }
        });
        p_create.add(add_cource, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 100, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mithila\\Documents\\anigif.gif")); // NOI18N
        p_create.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 190, 240));

        btn_clear.setBackground(new java.awt.Color(0, 102, 102));
        btn_clear.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("Clear");
        btn_clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_clear.setBorderPainted(false);
        btn_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear.setFocusPainted(false);
        btn_clear.setFocusable(false);
        btn_clear.setName("exit"); // NOI18N
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        p_create.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 100, 40));

        btn_back.setBackground(new java.awt.Color(0, 102, 102));
        btn_back.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Back");
        btn_back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_back.setBorderPainted(false);
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.setFocusPainted(false);
        btn_back.setFocusable(false);
        btn_back.setName("exit"); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        p_create.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 100, 40));

        jPanel2.add(p_create, "card2");

        p_remove.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("Enter Course Code :");

        txtFind.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_search_d.setBackground(new java.awt.Color(0, 102, 102));
        btn_search_d.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_search_d.setForeground(new java.awt.Color(255, 255, 255));
        btn_search_d.setText("Search");
        btn_search_d.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_search_d.setBorderPainted(false);
        btn_search_d.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_search_d.setFocusPainted(false);
        btn_search_d.setFocusable(false);
        btn_search_d.setName("exit"); // NOI18N
        btn_search_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_dActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("Remove Course Unit");

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mithila\\Documents\\anigif.gif")); // NOI18N

        txtCourse_code1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCourse_code1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourse_code1ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setText("Course Code :");

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel21.setText("Course Title :");

        txtCourse_title1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCourse_title1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourse_title1ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel22.setText("Course Coorinator :");

        txtCouse_co1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCouse_co1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCouse_co1ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel23.setText("Department :");

        txtdep1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtdep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdep1ActionPerformed(evt);
            }
        });

        btn_remove.setBackground(new java.awt.Color(0, 102, 102));
        btn_remove.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_remove.setForeground(new java.awt.Color(255, 255, 255));
        btn_remove.setText("Remove");
        btn_remove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_remove.setBorderPainted(false);
        btn_remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_remove.setFocusPainted(false);
        btn_remove.setFocusable(false);
        btn_remove.setName("exit"); // NOI18N
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        btn_back3.setBackground(new java.awt.Color(0, 102, 102));
        btn_back3.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_back3.setForeground(new java.awt.Color(255, 255, 255));
        btn_back3.setText("Back");
        btn_back3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_back3.setBorderPainted(false);
        btn_back3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back3.setFocusPainted(false);
        btn_back3.setFocusable(false);
        btn_back3.setName("exit"); // NOI18N
        btn_back3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back3ActionPerformed(evt);
            }
        });

        btn_back4.setBackground(new java.awt.Color(0, 102, 102));
        btn_back4.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_back4.setForeground(new java.awt.Color(255, 255, 255));
        btn_back4.setText("Clear");
        btn_back4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_back4.setBorderPainted(false);
        btn_back4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back4.setFocusPainted(false);
        btn_back4.setFocusable(false);
        btn_back4.setName("exit"); // NOI18N
        btn_back4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_removeLayout = new javax.swing.GroupLayout(p_remove);
        p_remove.setLayout(p_removeLayout);
        p_removeLayout.setHorizontalGroup(
            p_removeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_removeLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(p_removeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_removeLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(p_removeLayout.createSequentialGroup()
                        .addGap(0, 65, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addGap(103, 103, 103)
                        .addGroup(p_removeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(p_removeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_removeLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(btn_back3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btn_back4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_removeLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(p_removeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdep1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(p_removeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCourse_title1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCourse_code1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCouse_co1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(107, 107, 107))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_removeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btn_search_d, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        p_removeLayout.setVerticalGroup(
            p_removeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_removeLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel18)
                .addGap(17, 17, 17)
                .addGroup(p_removeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_search_d)
                    .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(p_removeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_removeLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(p_removeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCourse_code1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(p_removeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCourse_title1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(p_removeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCouse_co1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(p_removeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_removeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(p_removeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_back3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_back4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jPanel2.add(p_remove, "card4");

        p_update.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Update Course Units");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Enter Course Code :");

        txtSearch_u.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_search_course_u.setBackground(new java.awt.Color(0, 102, 102));
        btn_search_course_u.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_search_course_u.setForeground(new java.awt.Color(255, 255, 255));
        btn_search_course_u.setText("Search");
        btn_search_course_u.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_search_course_u.setBorderPainted(false);
        btn_search_course_u.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_search_course_u.setFocusPainted(false);
        btn_search_course_u.setFocusable(false);
        btn_search_course_u.setName("exit"); // NOI18N
        btn_search_course_u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_course_uActionPerformed(evt);
            }
        });

        txtCourse_code_u.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCourse_code_u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourse_code_uActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Course Code :");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setText("Course Title :");

        txtCourse_title_u.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCourse_title_u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourse_title_uActionPerformed(evt);
            }
        });

        txtCouse_co_u.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCouse_co_u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCouse_co_uActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setText("Course Coorinator :");

        txtdep_u.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtdep_u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdep_uActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setText("Department :");

        btn_update.setBackground(new java.awt.Color(0, 102, 102));
        btn_update.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Update");
        btn_update.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_update.setBorderPainted(false);
        btn_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_update.setFocusPainted(false);
        btn_update.setFocusable(false);
        btn_update.setName("exit"); // NOI18N
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_back1.setBackground(new java.awt.Color(0, 102, 102));
        btn_back1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_back1.setForeground(new java.awt.Color(255, 255, 255));
        btn_back1.setText("Back");
        btn_back1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_back1.setBorderPainted(false);
        btn_back1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back1.setFocusPainted(false);
        btn_back1.setFocusable(false);
        btn_back1.setName("exit"); // NOI18N
        btn_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back1ActionPerformed(evt);
            }
        });

        btn_back2.setBackground(new java.awt.Color(0, 102, 102));
        btn_back2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btn_back2.setForeground(new java.awt.Color(255, 255, 255));
        btn_back2.setText("Clear");
        btn_back2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_back2.setBorderPainted(false);
        btn_back2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back2.setFocusPainted(false);
        btn_back2.setFocusable(false);
        btn_back2.setName("exit"); // NOI18N
        btn_back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back2ActionPerformed(evt);
            }
        });

        table_course.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_course);

        javax.swing.GroupLayout p_updateLayout = new javax.swing.GroupLayout(p_update);
        p_update.setLayout(p_updateLayout);
        p_updateLayout.setHorizontalGroup(
            p_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_updateLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_updateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(txtSearch_u, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_search_course_u, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_updateLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(p_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_updateLayout.createSequentialGroup()
                        .addGroup(p_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(p_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCouse_co_u, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCourse_title_u, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCourse_code_u, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdep_u, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                    .addGroup(p_updateLayout.createSequentialGroup()
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btn_back1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_back2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        p_updateLayout.setVerticalGroup(
            p_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_updateLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel7)
                .addGap(37, 37, 37)
                .addGroup(p_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_search_course_u)
                    .addComponent(txtSearch_u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(p_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_updateLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(p_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCourse_code_u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(p_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCourse_title_u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(p_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCouse_co_u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(p_updateLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(p_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdep_u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(39, 39, 39)
                .addGroup(p_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_back1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_back2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jPanel2.add(p_update, "card3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(click_create)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12)))
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(click_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(click_delete))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel14)))
                .addGap(258, 258, 258))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(click_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(click_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(click_create)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void click_createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_click_createMouseClicked
        boolean set=false;
        p_update.setVisible(set);
        p_remove.setVisible(set);
        set=true;
        p_create.setVisible(set);
        
    }//GEN-LAST:event_click_createMouseClicked

    private void click_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_click_editMouseClicked
        boolean set=true;
        p_update.setVisible(set);
        set=false;
        p_create.setVisible(set);
        p_remove.setVisible(set);
        
    }//GEN-LAST:event_click_editMouseClicked

    private void click_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_click_deleteMouseClicked
        boolean set=true;
        p_remove.setVisible(set);
        set=false;
        p_update.setVisible(set);
        p_create.setVisible(set);
    }//GEN-LAST:event_click_deleteMouseClicked

    private void add_courceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_courceActionPerformed
       Courses cor=new Courses();
       //Admin adm=new Admin();
       Object dept=com_dep.getSelectedItem();
       String dep=dept.toString();
       cor.setCourseCode(txtCource_code.getText());
       cor.setCourseTitle(txtCourse_Title.getText());
       cor.setCourseCo(txtCourse_co.getText());
       cor.setDep(dep);
       cor.addCourse();
    }//GEN-LAST:event_add_courceActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        txtCource_code.setText(null);
        txtCourse_Title.setText(null);
        txtCourse_co.setText(null);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        form9 f9=new form9();
        f9.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_search_course_uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_course_uActionPerformed

        //get the values from all text feilds to variables

        String search=txtSearch_u.getText();
        if(search.equals("")){
            JOptionPane.showMessageDialog(null, "You must have to enter Reg Number!.. Otherwise how to find relavent feild!.");
        }
        else{
            Courses cor=new Courses();
            
            ResultSet rs=cor.updateCourse(search);
            try{
                if(rs.next()){
                    txtCourse_code_u.setText(rs.getString("course_code"));
                    txtCourse_title_u.setText(rs.getString("course_title"));
                    txtCouse_co_u.setText(rs.getString("course_co"));
                    txtdep_u.setText(rs.getString("department"));
                }
            }catch(Exception e){
                //user not found
                JOptionPane.showMessageDialog(null, "User not Found!..");
            }
        }
    }//GEN-LAST:event_btn_search_course_uActionPerformed

    private void txtCourse_code_uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourse_code_uActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourse_code_uActionPerformed

    private void txtCourse_title_uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourse_title_uActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourse_title_uActionPerformed

    private void txtCouse_co_uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCouse_co_uActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCouse_co_uActionPerformed

    private void txtdep_uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdep_uActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdep_uActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        Courses cor=new Courses();
        cor.setCourseCode(txtCourse_code_u.getText());
        cor.setCourseTitle(txtCourse_title_u.getText());
        cor.setCourseCo(txtCouse_co_u.getText());
        cor.setDep(txtdep_u.getText());
        cor.updateCourseData(txtCourse_code_u.getText());

        //in Here trying to get and values to textfeilds within database

    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back1ActionPerformed
        //back to admin panel
        form9 f9=new form9();
        f9.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_back1ActionPerformed

    private void btn_back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back2ActionPerformed
                //Reset all text inputs
                txtCourse_code_u.setText(null);
                txtCourse_title_u.setText(null);
                txtCouse_co_u.setText(null);
                txtdep_u.setText(null);
    }//GEN-LAST:event_btn_back2ActionPerformed

    private void btn_search_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_dActionPerformed

        //get the values from all text feilds to variables

        String search=txtFind.getText();
        if(search.equals("")){
            JOptionPane.showMessageDialog(null, "You must have to enter Course Code!.. Otherwise how to find relavent feild!.");
        }
        else{
            Courses cor=new Courses();
            
            ResultSet rs=cor.updateCourse(search);
            try{
                if(rs.next()){
                    txtCourse_code1.setText(rs.getString("course_code"));
                    txtCourse_title1.setText(rs.getString("course_title"));
                    txtCouse_co1.setText(rs.getString("course_co"));
                    txtdep1.setText(rs.getString("department"));
                }
            }catch(Exception e){
                //user not found
                JOptionPane.showMessageDialog(null, "User not Found!..");
            }
        }
    }//GEN-LAST:event_btn_search_dActionPerformed

    private void txtCourse_code1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourse_code1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourse_code1ActionPerformed

    private void txtCourse_title1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourse_title1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourse_title1ActionPerformed

    private void txtCouse_co1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCouse_co1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCouse_co1ActionPerformed

    private void txtdep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdep1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdep1ActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
         Courses c=new Courses();
         c.setCourseCode(txtCourse_code1.getText());
         c.setCourseTitle(txtCourse_title1.getText());
         c.setCourseCo(txtCouse_co1.getText());
         c.setDep(txtdep1.getText());
         c.removeCourseData(txtCourse_code1.getText());
    }//GEN-LAST:event_btn_removeActionPerformed

    private void btn_back3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back3ActionPerformed
        // TODO add your handling code here:
        form9 f9=new form9();
        f9.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_back3ActionPerformed

    private void btn_back4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back4ActionPerformed
        
            txtCourse_code1.setText(null);
            txtCourse_title1.setText(null);
            txtCouse_co1.setText(null);
            txtdep1.setText(null);
    }//GEN-LAST:event_btn_back4ActionPerformed

    void showdata()
    {
        Connection con=MyConnection.getConnection();
        try {
            String sql="select *from courses";
            PreparedStatement ps=con.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            table_course.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form13().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_cource;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_back1;
    private javax.swing.JButton btn_back2;
    private javax.swing.JButton btn_back3;
    private javax.swing.JButton btn_back4;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_search_course_u;
    private javax.swing.JButton btn_search_d;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel click_create;
    private javax.swing.JLabel click_delete;
    private javax.swing.JLabel click_edit;
    private javax.swing.JComboBox<String> com_dep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel p_create;
    private javax.swing.JPanel p_remove;
    private javax.swing.JPanel p_update;
    private javax.swing.JTable table_course;
    private javax.swing.JTextField txtCource_code;
    private javax.swing.JTextField txtCourse_Title;
    private javax.swing.JTextField txtCourse_co;
    public javax.swing.JTextField txtCourse_code1;
    public javax.swing.JTextField txtCourse_code_u;
    public javax.swing.JTextField txtCourse_title1;
    public javax.swing.JTextField txtCourse_title_u;
    public javax.swing.JTextField txtCouse_co1;
    public javax.swing.JTextField txtCouse_co_u;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtSearch_u;
    public javax.swing.JTextField txtdep1;
    public javax.swing.JTextField txtdep_u;
    // End of variables declaration//GEN-END:variables
}
