
import com.mysql.cj.xdevapi.Result;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mithila
 */
public class form30 extends javax.swing.JFrame {

    /**
     * Creates new form form30
     */
    public form30() {
        initComponents();
        showAttendance();
        Hide();
        showAtt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        view_eligibility = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtFind_reg_no2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        eligibilitys = new javax.swing.JTable();
        message3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtreg_v = new javax.swing.JLabel();
        txtsub_v = new javax.swing.JLabel();
        txtover_v = new javax.swing.JLabel();
        txttheory_v = new javax.swing.JLabel();
        txtpractical_v = new javax.swing.JLabel();
        txtca_v = new javax.swing.JLabel();
        add_eligibility = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtFind_reg_no1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtFind_subject_code = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtreg1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtsub1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txteligibility = new javax.swing.JLabel();
        add_time_table3_et = new javax.swing.JButton();
        message2 = new javax.swing.JLabel();
        showt = new javax.swing.JLabel();
        tangree = new javax.swing.JLabel();
        thappy = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        showp = new javax.swing.JLabel();
        phappy = new javax.swing.JLabel();
        pangree = new javax.swing.JLabel();
        view_attendance = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attendance = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtFind_reg_no = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFind_sub_code = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtreg = new javax.swing.JLabel();
        txtsession = new javax.swing.JLabel();
        txtsub = new javax.swing.JLabel();
        txtstatus = new javax.swing.JLabel();
        txttype = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setLayout(new java.awt.CardLayout());

        view_eligibility.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 102));
        jLabel21.setText("View Eligibility");

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel22.setText("Reg No :");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_search_64px.png"))); // NOI18N
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });

        eligibilitys.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        eligibilitys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eligibilitysMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(eligibilitys);

        message3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        message3.setForeground(new java.awt.Color(255, 0, 0));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel25.setText("Reg No :");

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel26.setText("Subject Code :");

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel27.setText("Overroll Eligibility :");

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setText("Practical Eligibility :");

        jLabel29.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel29.setText("Theory Eligibility :");

        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel30.setText("CA Eligibility :");

        txtreg_v.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtreg_v.setText("xxxxxxxxxx");

        txtsub_v.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtsub_v.setText("xxxxxxxxxx");

        txtover_v.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtover_v.setText("xxxxxxxxxx");

        txttheory_v.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txttheory_v.setText("xxxxxxxxxx");

        txtpractical_v.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtpractical_v.setText("xxxxxxxxxx");

        txtca_v.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtca_v.setText("xxxxxxxxxx");

        javax.swing.GroupLayout view_eligibilityLayout = new javax.swing.GroupLayout(view_eligibility);
        view_eligibility.setLayout(view_eligibilityLayout);
        view_eligibilityLayout.setHorizontalGroup(
            view_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_eligibilityLayout.createSequentialGroup()
                .addGroup(view_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(view_eligibilityLayout.createSequentialGroup()
                        .addGroup(view_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(view_eligibilityLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(view_eligibilityLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFind_reg_no2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(view_eligibilityLayout.createSequentialGroup()
                        .addGroup(view_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(view_eligibilityLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(message3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_eligibilityLayout.createSequentialGroup()
                                .addContainerGap(155, Short.MAX_VALUE)
                                .addGroup(view_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel30))
                                .addGap(51, 51, 51)
                                .addGroup(view_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtca_v)
                                    .addComponent(txtpractical_v)
                                    .addComponent(txttheory_v)
                                    .addComponent(txtover_v)
                                    .addComponent(txtsub_v)
                                    .addComponent(txtreg_v))
                                .addGap(142, 142, 142)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        view_eligibilityLayout.setVerticalGroup(
            view_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_eligibilityLayout.createSequentialGroup()
                .addGroup(view_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(view_eligibilityLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(view_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtFind_reg_no2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(view_eligibilityLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(view_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(view_eligibilityLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(view_eligibilityLayout.createSequentialGroup()
                        .addGroup(view_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtreg_v))
                        .addGap(29, 29, 29)
                        .addGroup(view_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtsub_v))
                        .addGap(35, 35, 35)
                        .addGroup(view_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtover_v))
                        .addGap(35, 35, 35)
                        .addGroup(view_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txttheory_v))
                        .addGap(41, 41, 41)
                        .addGroup(view_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtpractical_v))
                        .addGap(40, 40, 40)
                        .addGroup(view_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(txtca_v))
                        .addGap(87, 87, 87)
                        .addComponent(message3)
                        .addGap(34, 34, 34))))
        );

        jPanel2.add(view_eligibility, "card4");

        add_eligibility.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Add Eligibility");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setText("Reg No :");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setText("Subject Code :");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_search_64px.png"))); // NOI18N
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        txtreg1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtreg1.setText("xxxxxxxxxx");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setText("Subject Code :");

        txtsub1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtsub1.setText("xxxxxxxxxx");

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setText("Eligibility :");

        txteligibility.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txteligibility.setText("xxxxxxxxxx");

        add_time_table3_et.setBackground(new java.awt.Color(0, 102, 102));
        add_time_table3_et.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        add_time_table3_et.setForeground(new java.awt.Color(255, 255, 255));
        add_time_table3_et.setText("Add");
        add_time_table3_et.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_time_table3_et.setBorderPainted(false);
        add_time_table3_et.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_time_table3_et.setFocusPainted(false);
        add_time_table3_et.setFocusable(false);
        add_time_table3_et.setName("exit"); // NOI18N
        add_time_table3_et.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_time_table3_etActionPerformed(evt);
            }
        });

        message2.setForeground(new java.awt.Color(204, 0, 0));

        showt.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        showt.setText("Theory Eligibility");

        tangree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_angry_96px.png"))); // NOI18N

        thappy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_happy_96px.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setText("Reg No :");

        showp.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        showp.setText("Practical Eligibility");

        phappy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_happy_96px.png"))); // NOI18N

        pangree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_angry_96px.png"))); // NOI18N

        javax.swing.GroupLayout add_eligibilityLayout = new javax.swing.GroupLayout(add_eligibility);
        add_eligibility.setLayout(add_eligibilityLayout);
        add_eligibilityLayout.setHorizontalGroup(
            add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_eligibilityLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_eligibilityLayout.createSequentialGroup()
                        .addGroup(add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_eligibilityLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFind_reg_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_eligibilityLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFind_subject_code, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(add_eligibilityLayout.createSequentialGroup()
                        .addGroup(add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel24))
                        .addGap(47, 47, 47)
                        .addGroup(add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsub1)
                            .addGroup(add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txteligibility, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtreg1))))
                    .addComponent(add_time_table3_et, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(message2)
                    .addComponent(jLabel20))
                .addGroup(add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_eligibilityLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(add_eligibilityLayout.createSequentialGroup()
                                .addComponent(showt)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(showp)))
                    .addGroup(add_eligibilityLayout.createSequentialGroup()
                        .addGroup(add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(add_eligibilityLayout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(phappy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pangree))
                            .addGroup(add_eligibilityLayout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(thappy)
                                .addGap(18, 18, 18)
                                .addComponent(tangree)))
                        .addContainerGap(186, Short.MAX_VALUE))))
            .addGroup(add_eligibilityLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        add_eligibilityLayout.setVerticalGroup(
            add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_eligibilityLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel14)
                .addGroup(add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_eligibilityLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(add_eligibilityLayout.createSequentialGroup()
                                .addGroup(add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtFind_reg_no1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txtFind_subject_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel17))
                        .addGap(91, 91, 91)
                        .addGroup(add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtreg1)
                            .addComponent(jLabel24)))
                    .addGroup(add_eligibilityLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(showt)
                        .addGap(45, 45, 45)
                        .addGroup(add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tangree, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thappy, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_eligibilityLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtsub1))
                        .addGap(28, 28, 28)
                        .addGroup(add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txteligibility))
                        .addGap(39, 39, 39)
                        .addComponent(message2)
                        .addGap(18, 18, 18)
                        .addComponent(add_time_table3_et, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(add_eligibilityLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel18)
                        .addGap(23, 23, 23)
                        .addComponent(showp)
                        .addGap(31, 31, 31)
                        .addGroup(add_eligibilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pangree, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phappy, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jPanel2.add(add_eligibility, "card3");

        view_attendance.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("View Attendance");

        attendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        attendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendanceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(attendance);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Reg No :");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_search_64px.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Subject Code :");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Reg No :");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("Session No :");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Subject Code :");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setText("Type :");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setText("Status :");

        txtreg.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtreg.setText("xxxxxxxxxx");

        txtsession.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtsession.setText("xxxxxxxxxx");

        txtsub.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtsub.setText("xxxxxxxxxx");

        txtstatus.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtstatus.setText("xxxxxxxxxx");

        txttype.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txttype.setText("xxxxxxxxxx");

        message.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout view_attendanceLayout = new javax.swing.GroupLayout(view_attendance);
        view_attendance.setLayout(view_attendanceLayout);
        view_attendanceLayout.setHorizontalGroup(
            view_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_attendanceLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(view_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(view_attendanceLayout.createSequentialGroup()
                        .addGroup(view_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(view_attendanceLayout.createSequentialGroup()
                                .addGroup(view_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(view_attendanceLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtFind_reg_no, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(view_attendanceLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFind_sub_code, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_attendanceLayout.createSequentialGroup()
                                        .addGroup(view_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addGap(43, 43, 43)
                                        .addGroup(view_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtreg)
                                            .addComponent(txtsession)
                                            .addComponent(txtstatus)
                                            .addComponent(txttype)
                                            .addComponent(txtsub))))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(view_attendanceLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        view_attendanceLayout.setVerticalGroup(
            view_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_attendanceLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(view_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(view_attendanceLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(view_attendanceLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(view_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(view_attendanceLayout.createSequentialGroup()
                                .addGroup(view_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtFind_reg_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(view_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtFind_sub_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(66, 66, 66)
                        .addGroup(view_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtreg))
                        .addGap(35, 35, 35)
                        .addGroup(view_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtsub))
                        .addGap(33, 33, 33)
                        .addGroup(view_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtsession))
                        .addGap(35, 35, 35)
                        .addGroup(view_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txttype))
                        .addGap(43, 43, 43)
                        .addGroup(view_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtstatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(message)
                        .addGap(21, 21, 21))))
        );

        jPanel2.add(view_attendance, "card2");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cource.png"))); // NOI18N
        jLabel1.setText("Add Eligibility");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cource.png"))); // NOI18N
        jLabel2.setText("View Eligibility");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cource.png"))); // NOI18N
        jLabel3.setText("View Attendance");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit3.png"))); // NOI18N
        jLabel4.setText("Exit");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel3)
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addGap(78, 78, 78)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        boolean flag=true;
        add_eligibility.setVisible(flag);
        flag=false;
        view_attendance.setVisible(flag);
        view_eligibility.setVisible(flag);
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
         boolean flag=true;
         view_eligibility.setVisible(flag);
         flag=false;
         add_eligibility.setVisible(flag);
         view_attendance.setVisible(flag);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        boolean flag=true;
        view_attendance.setVisible(flag);
        flag=false;
        view_eligibility.setVisible(flag);
        add_eligibility.setVisible(flag);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        form26 f26=new form26();
        f26.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        txtreg.setText("xxxxxxxxxx");
        txtsub.setText("xxxxxxxxxx");
        txtsession.setText("xxxxxxxxxx");
        txttype.setText("xxxxxxxxxx");
        txtstatus.setText("xxxxxxxxxx");

        String reg=txtFind_reg_no.getText();
        String sub_code=txtFind_sub_code.getText();
        if(reg.equals("")||sub_code.equals(""))
        message.setText("You should have to mention Reg Number!");
        else{
            Connection con=MyConnection.getConnection();
            try {
                message.setText(null);

                String sql="select *from attendance where reg_no='"+reg+"' AND subject_code='"+sub_code+"' ORDER BY session_no";
                PreparedStatement ps=con.prepareStatement(sql);
                ResultSet rs=ps.executeQuery();
                attendance.setModel(DbUtils.resultSetToTableModel(rs));

                //showGrade();
            } catch (Exception e) {
            }
            
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void attendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseClicked
        // TODO add your handling code here:
        int r=attendance.getSelectedRow();
        String reg=attendance.getValueAt(r, 0).toString();
        String sub_code=attendance.getValueAt(r, 1).toString();
        String session=attendance.getValueAt(r, 2).toString();
        String type=attendance.getValueAt(r, 3).toString();
        String status=attendance.getValueAt(r, 4).toString();
        
        txtreg.setText(reg);
        txtsub.setText(sub_code);
        txtsession.setText(session);
        txttype.setText(type);
        txtstatus.setText(status);
    }//GEN-LAST:event_attendanceMouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        Attendance att=new Attendance();
        String reg=txtFind_reg_no1.getText();
        String sub_code=txtFind_subject_code.getText();
        boolean flag=true;
        
        if(reg.equals("")||sub_code.equals(""))
            message2.setText("You have to mention Reg No and Subject Code!");
        else
        {
            txtreg1.setText(reg);
            txtsub1.setText(sub_code);
            if(sub_code.equals("ICT2162")){
                 message2.setText(null);
                 txteligibility.setText(att.getEligibilityTheory(reg, sub_code));
                 if(att.getEligibilityTheory(reg, sub_code).equals("Eligible"))
                 {
                     showt.setVisible(flag);
                     thappy.setVisible(flag);
                 }
                 else
                 {
                     showt.setVisible(flag);
                     tangree.setVisible(flag);
                 }    
            }     
            else{
                message2.setText(null);
                txteligibility.setText(att.getEligibility(reg, sub_code));
                if(att.getEligibilityPractical(reg, sub_code).equals("Eligible"))
                {
                    showt.setVisible(flag);
                    thappy.setVisible(flag);
                    showp.setVisible(flag);
                    phappy.setVisible(flag);
                } 
                else{
                    showt.setVisible(flag);
                    tangree.setVisible(flag);
                    showp.setVisible(flag);
                    pangree.setVisible(flag);
                }
            }    
            
            
        }    
    }//GEN-LAST:event_jLabel17MouseClicked

    private void add_time_table3_etActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_time_table3_etActionPerformed
        // TODO add your handling code here:
        if(txtreg1.getText().equals("xxxxxxxxxx")||txtsub1.getText().equals("xxxxxxxxxx")||txteligibility.getText().equals("xxxxxxxxxx"))
        message2.setText(" Not Selected");
        else
        {
            try {
                Connection con=MyConnection.getConnection();
                String sql="INSERT INTO eligibility VALUES('"+txtreg1.getText()+"','"+txtsub1.getText()+"','"+txteligibility.getText()+"')";
                PreparedStatement ps=con.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Data added Successfully!.");
                Hide();
                txtFind_reg_no1.setText(null);
                txtFind_subject_code.setText(null);
                txtreg1.setText("xxxxxxxxxx");
                txtsub1.setText("xxxxxxxxxx");
                txteligibility.setText("xxxxxxxxxx");
            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_add_time_table3_etActionPerformed

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        String reg=txtFind_reg_no2.getText();
        if(reg.equals(""))
            message3.setText("You have to mention Reg No!..");
        else
        {
            message3.setText(null);
            Connection con=MyConnection.getConnection();
            try {
                String sql="SELECT *FROM eligibility WHERE reg_no='"+reg+"'";
                PreparedStatement ps=con.prepareStatement(sql);
                ResultSet rs=ps.executeQuery();
                eligibilitys.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (Exception e) {
            }
            txtreg_v.setText("xxxxxxxxxx");
            txtsub_v.setText("xxxxxxxxxx");
            txtover_v.setText("xxxxxxxxxx");
            txttheory_v.setText("xxxxxxxxxx");
            txtpractical_v.setText("xxxxxxxxxx");
            txtca_v.setText("xxxxxxxxxx");
        }
        
    }//GEN-LAST:event_jLabel23MouseClicked

    private void eligibilitysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eligibilitysMouseClicked
        // TODO add your handling code here:
        Attendance att=new Attendance();
        int r=eligibilitys.getSelectedRow();
        String reg=eligibilitys.getValueAt(r, 0).toString();
        String sub_code=eligibilitys.getValueAt(r, 1).toString();
        String status=eligibilitys.getValueAt(r, 2).toString();
       
        txtreg_v.setText(reg);
        txtsub_v.setText(sub_code);
        txtover_v.setText(status);
        txttheory_v.setText(att.getEligibilityTheory(reg, sub_code));
        txtpractical_v.setText(att.getEligibilityPractical(reg, sub_code));
        if(sub_code.equals("ICT2162")){
             txtpractical_v.setText("Theory Only");
             txtca_v.setText(att.getCAEligibility2(reg,sub_code));
             att.addCA(reg,sub_code,att.getCAEligibility2(reg,sub_code));
        }     
        else{
            txtca_v.setText(att.getCAEligibility(reg,sub_code));
            att.addCA(reg, sub_code, att.getCAEligibility(reg, sub_code));
        }    
    }//GEN-LAST:event_eligibilitysMouseClicked

    /**
     * @param args the command line arguments
     */
    void showAttendance()
    {
        Connection con=MyConnection.getConnection();
        try {
            String sql="SELECT *FROM attendance";
            PreparedStatement ps=con.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            attendance.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    
    void Hide()
    {
        boolean flag=false;
        showt.setVisible(flag);
        showp.setVisible(flag);
        thappy.setVisible(flag);
        tangree.setVisible(flag);
        phappy.setVisible(flag);
        pangree.setVisible(flag);
    } 
    
    void showAtt()
    {
        Connection con=MyConnection.getConnection();
        try {
            String sql="SELECT *FROM eligibility";
            PreparedStatement ps=con.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            eligibilitys.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form30.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form30.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form30.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form30.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form30().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add_eligibility;
    private javax.swing.JButton add_time_table3_et;
    private javax.swing.JTable attendance;
    private javax.swing.JTable eligibilitys;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel message;
    private javax.swing.JLabel message2;
    private javax.swing.JLabel message3;
    private javax.swing.JLabel pangree;
    private javax.swing.JLabel phappy;
    private javax.swing.JLabel showp;
    private javax.swing.JLabel showt;
    private javax.swing.JLabel tangree;
    private javax.swing.JLabel thappy;
    private javax.swing.JTextField txtFind_reg_no;
    private javax.swing.JTextField txtFind_reg_no1;
    private javax.swing.JTextField txtFind_reg_no2;
    private javax.swing.JTextField txtFind_sub_code;
    private javax.swing.JTextField txtFind_subject_code;
    private javax.swing.JLabel txtca_v;
    private javax.swing.JLabel txteligibility;
    private javax.swing.JLabel txtover_v;
    private javax.swing.JLabel txtpractical_v;
    private javax.swing.JLabel txtreg;
    private javax.swing.JLabel txtreg1;
    private javax.swing.JLabel txtreg_v;
    private javax.swing.JLabel txtsession;
    private javax.swing.JLabel txtstatus;
    private javax.swing.JLabel txtsub;
    private javax.swing.JLabel txtsub1;
    private javax.swing.JLabel txtsub_v;
    private javax.swing.JLabel txttheory_v;
    private javax.swing.JLabel txttype;
    private javax.swing.JPanel view_attendance;
    private javax.swing.JPanel view_eligibility;
    // End of variables declaration//GEN-END:variables
}
